# Generated by Django 3.2.13 on 2022-05-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('post_limit', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('image_url', models.URLField()),
                ('score', models.BigIntegerField()),
                ('is_telegram_posted', models.BooleanField(default=False)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawlers.redditsource')),
            ],
        ),
    ]
