# Generated by Django 3.2.13 on 2022-05-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='is_instagram_posted',
            field=models.BooleanField(default=False),
        ),
    ]
