# Generated by Django 3.2.13 on 2022-05-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0002_auto_20220514_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
