# Generated by Django 3.2.13 on 2022-05-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chat_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('reddit_sources', models.ManyToManyField(to='crawlers.RedditSource')),
            ],
        ),
    ]
