# Generated by Django 3.2.13 on 2022-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_instagramprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramprofile',
            name='hashtags',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
