# Generated by Django 3.2.13 on 2022-05-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_alter_instagramprofile_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramprofile',
            name='hashtags',
            field=models.TextField(),
        ),
    ]
