# Generated by Django 3.2.13 on 2022-05-29 17:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0004_alter_instagramprofile_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagrapiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('comment_phrases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('login_settings', models.JSONField()),
                ('main_hashtag', models.CharField(max_length=50)),
                ('like_posts', models.BooleanField(default=True)),
                ('follow_users', models.BooleanField(default=True)),
            ],
        ),
    ]
