# Generated by Django 3.2.13 on 2022-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0007_auto_20220620_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrapiconfig',
            name='post_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='instagrapiconfig',
            name='mention_author',
            field=models.BooleanField(default=True),
        ),
    ]
