# Generated by Django 3.2.13 on 2022-07-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0003_auto_20220618_1456'),
        ('posters', '0008_auto_20220620_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('posting_hashtags', models.TextField(blank=True, null=True)),
                ('mention_author', models.BooleanField(default=True)),
                ('post_interval', models.PositiveIntegerField(default=360, help_text='Run post every N minutes')),
                ('last_post_date', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postconfig', to='posters.instagrapiconfig')),
                ('reddit_sources', models.ManyToManyField(blank=True, to='crawlers.RedditSource')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramLikePromoteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, help_text='Search posts and authors with this hashtag', max_length=50, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('promote_interval', models.PositiveIntegerField(default=180, help_text='Run likes promotion every N minutes')),
                ('likes_per_promotion', models.PositiveIntegerField(default=20, help_text='Count of likes for 1 Promotion task')),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likeconfig', to='posters.instagrapiconfig')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramHashtagFollowPromoteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('hashtag', models.CharField(help_text='Search posts and authors with this hashtag', max_length=50)),
                ('promote_interval', models.PositiveIntegerField(default=180, help_text='Run follow promotion every N minutes')),
                ('follow_per_promotion', models.PositiveIntegerField(default=10, help_text='Count of follow for 1 Promotion task')),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followconfig', to='posters.instagrapiconfig')),
            ],
        ),
    ]
