# Generated by Django 3.2.13 on 2022-07-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0009_instagramhashtagfollowpromoteconfig_instagramlikepromoteconfig_instagrampostconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampostconfig',
            name='use_location_in_post',
            field=models.BooleanField(default=True),
        ),
    ]
